name: Implementation Task
description: Create a development task linked to a feature
title: "[Task]: "
labels: ["task"]
body:
  - type: markdown
    attributes:
      value: |
        Create an implementation task. Add this as a sub-issue of a feature task on the Feature Board.
  - type: input
    id: estimate-hours
    attributes:
      label: Estimate (Hours)
      description: How many hours do you estimate this task will take?
      placeholder: "e.g., 4"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be implemented?
      placeholder: Describe the work to be done...
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How do we know this task is done?
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information, links, or references.
      placeholder: Additional context...
    validations:
      required: false
